boxLayoutEx:

<boxLayoutEx>
    orientation: "vertical"
    Button:
        text: "Button"
        color: 1, 1, 0, 0.7
    Label:
        text: "Label"
        color: 1, 0, 0, 0.7

<mainWidget>:
    Button:
        text: "Button"
        size: '60dp', "20dp"
        pos: "0dp", "0dp"
        color: 1, 1, 0, 0.7
    Label:
        text: "Label"
        size: '60dp', "20dp"
        pos: "0", "20dp"
        color: 1, 0, 0, 0.7